#!/usr/bin/env bash
#
# Copyright Dansk Bibliotekscenter a/s. Licensed under GPLv3
# See license text in LICENSE.md
#

log-tracer_home="$HOME/.log-tracer"
log-tracer_archive="${log-tracer_home}/archive"
log-tracer_bin="${log-tracer_home}/bin"
log-tracer_url=http://mavenrepo.dbc.dk/content/repositories/releases/dk/dbc/log-tracer

function get_current_version {
    local current_version
    if [ -f ${log-tracer_home}/version ]; then
        current_version=`cat ${log-tracer_home}/version`
    else
        current_version=0
    fi
    echo ${current_version}
}

function get_latest_version {
    local latest_version=`
        curl -s "${log-tracer_url}/maven-metadata.xml" | \
        grep "<release>.*</release>" | \
        sed -e "s#\(.*\)\(<release>\)\(.*\)\(</release>\)\(.*\)#\3#g"`
    echo ${latest_version}
}

function install {
    if [ -z $(which curl) ]; then
        echo "curl not found."
        echo ""
        echo "======================================================================================================"
        echo " Please install curl on your system using your favourite package manager."
        echo ""
        echo " Restart after installing curl."
        echo "======================================================================================================"
        echo ""
        exit 1
    fi

    if [ -z $(which unzip) ]; then
        echo "unzip not found."
        echo ""
        echo "======================================================================================================"
        echo " Please install unzip on your system using your favourite package manager."
        echo ""
        echo " Restart after installing unzip."
        echo "======================================================================================================"
        echo ""
        exit 1
    fi

    if [ -z $(which java) ]; then
        echo "java not found."
        echo ""
        echo "======================================================================================================"
        echo " Please install java on your system using your favourite package manager."
        echo ""
        echo " Restart after installing java."
        echo "======================================================================================================"
        echo ""
        exit 1
    fi

    mkdir -pv "$log-tracer_archive"
    mkdir -pv "$log-tracer_bin"

    local current_version=`get_current_version`
    local latest_version=`get_latest_version`

    if [ "$current_version" != "$latest_version" ]; then
        echo "Installing version ${latest_version}"
        curl -sL ${log-tracer_url}/${latest_version}/log-tracer-${latest_version}.jar -o ${log-tracer_archive}/log-tracer-${latest_version}.jar
        if [ $? -eq 0 ]; then
            [ -e ${log-tracer_archive}/log-tracer-current.jar ] && rm ${log-tracer_archive}/log-tracer-current.jar
            ln -s ${log-tracer_archive}/log-tracer-${latest_version}.jar ${log-tracer_archive}/log-tracer-current.jar
            unzip -o ${log-tracer_archive}/log-tracer-current.jar log-tracer -d ${log-tracer_bin}
            chmod a+x ${log-tracer_bin}/log-tracer
            echo ${latest_version} > ${log-tracer_home}/version
        fi

        if [ ! -f ~/.bash_aliases ]; then
            touch ~/.bash_aliases
        fi

        grep "log-tracer=~/.log-tracer/bin/log-tracer" ~/.bash_aliases ||
            echo -e "\nalias log-tracer=~/.log-tracer/bin/log-tracer" >> ~/.bash_aliases ; . ~/.bash_aliases
    else
        echo "Already at latest version ${latest_version}"
    fi
}

function selfupdate {
    local current_version=`get_current_version`
    local latest_version=`get_latest_version`
    if [ "$current_version" != "$latest_version" ]; then
        curl -sL ${log-tracer_url}/${latest_version}/log-tracer-${latest_version}.jar -o /tmp/log-tracer-${latest_version}.jar
        unzip -qo /tmp/log-tracer-${latest_version}.jar log-tracer -d /tmp
        bash /tmp/log-tracer --install
    else
        echo "Already at latest version ${latest_version}"
    fi
}

function version {
    local current_version=`get_current_version`
    local latest_version=`get_latest_version`
    echo ${current_version}
    if [ "$current_version" != "$latest_version" ]; then
        echo "A new version ${latest_version} is available, update with 'log-tracer --selfupdate'"
    fi
}

case "$1" in
    --install)
    install
    ;;
    --version)
    version
    ;;
    -h)
    echo "usage: log-tracer --version"
    echo "usage: log-tracer --selfupdate"
    java -jar ${log-tracer_archive}/log-tracer-current.jar -h
    ;;
    --selfupdate)
    selfupdate
    ;;
    *)
    java -jar ${log-tracer_archive}/log-tracer-current.jar "$@"
    ;;
esac
